### ISSUE TITLE
Include a way to introduce a "ignore the node_modules" folder process or similar

### ISSUE THREAD

**Issue by voor** [paketo-buildpacks/node-run-script#13]
## What happened?

* What were you attempting to do?

I am using the node-run-script to build static frontend code and then serving it up from another container, I want a way to say "thank you for your help node, but I don't need you anymore" right now I'm committing this file into my source code:

`project.toml`:

```
[build]
include = [
    "nginx.conf",
    "mime.types",
    "build/"
]
```

This works great, but it requires me to make sure the code exists in every source code repository, when I'd rather include this elsewhere.

* What did you expect to happen?

I did not expect `node_modules` to be there after just using the node-run-script.

* What was the actual behavior? Please provide log output, if possible.

## Build Configuration

* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you
  using? Please include a version.

kpack and Tanzu Build Service

* What buildpacks are you using? Please include versions.

`gcr.io/paketo-buildpacks/nodejs:0.6.0`

* What builder are you using? If custom, can you provide the output from `pack
  inspect-builder <builder>`?

* Can you provide a sample app or relevant configuration (`buildpack.yml`,
  `nginx.conf`, etc.)?

## Checklist

* [ ] I have included log output.
* [ ] The log output includes an error message.
* [ ] I have included steps for reproduction.

**Comment by arjun024** [comment]
@voor Thank you for filing the issue. This buildpack is currently designed in a way that it asks an upstream buildpack to run `npm/yarn install` so that any tools required to run the script is available. For e.g. an angular build script like `"build": "ng build"` needs the `ng` tool.

For clarity, you are requesting an option to turn off package installation (i.e. `npm/yarn install`) and simply use this buildpack to run a script during the build process?

**Comment by voor** [comment]
No, my concern is that when this buildpack is run the resulting output still contains the `node_modules` folder, I want to make sure that `node_modules` folder is *not* present in the resulting image.

**Comment by ryanmoran** [comment]
I think this is an argument to include a buildpack like https://github.com/ForestEckhardt/source-removal in the build plan.

**Comment by ryanmoran** [comment]
@ForestEckhardt what do you think?

**Comment by ForestEckhardt** [comment]
I think that could work. I don't know if there would be issues seeing as how the `node_modules` directory is on a layer. Also the way that `source-removal` is currently structured you need to provide a list of files that you want included in the final image not a list of files that you want removed. So it might be a bit tedious for this use case. I could expand the functionality to selective delete things on the setting of a different env var though.

**Comment by voor** [comment]
> I think that could work. I don't know if there would be issues seeing as how the `node_modules` directory is on a layer. Also the way that `source-removal` is currently structured you need to provide a list of files that you want included in the final image not a list of files that you want removed. So it might be a bit tedious for this use case. I could expand the functionality to selective delete things on the setting of a different env var though.

As long as `$BP_INCLUDE_FILES="nginx.conf,mime.types,build/*"` works as intended then this might be exactly what I'd want.

**Comment by ForestEckhardt** [comment]
@voor Yeah, the only thing to keep in mind is that those will be path separated. So it will look a little more like this `$BP_INCLUDE_FILES="nginx.conf:mime.types:build/*"`

**Comment by fg-j** [comment]
I'm pretty sure that [this RFC](https://github.com/paketo-buildpacks/rfcs/pull/139) will ultimately result in support for this use case. @voor  take a look to see if that will meet your needs.

**Comment by voor** [comment]
Yes, this RFC meets my needs in-line with previous discussions, and I was able to achieve something similar by using https://github.com/ForestEckhardt/source-removal and populating $BP_INCLUDE_FILES="nginx.conf:mime.types:build/*" alongside `BP_NODE_RUN_SCRIPTS`.  My lingering concerns were purely from a distribution and installation experience, which then becomes out of scope of Paketo.

**Comment by mhdawson** [comment]
@voor I think from my read of the issue your requirement was addressed. If so would I think we should close this issue.

**Comment by voor** [comment]
So today things look a LOT better, since specifically the `node_modules` folder appears to now be a symlink to `/tmp/nodule_modules` -- that is a huge improvement when this thread was brought up a few years ago.  _However_, I'm still seeing some other "wastes of space" -- namely things like the `.git` folder, the entire `src` folder, and the `build` folder.

However, since I see `paketo-buildpacks/source-removal` maybe the trick is just running this again with the variable I mentioned in an earlier comment populated.

I'm using a very basic create-react-app with `pack build create-react-app:latest -e BP_WEB_SERVER=nginx`

```
7 of 11 buildpacks participating
paketo-buildpacks/ca-certificates 3.8.5
paketo-buildpacks/node-engine     4.1.11
paketo-buildpacks/yarn            1.3.15
paketo-buildpacks/yarn-install    2.0.9
paketo-buildpacks/node-run-script 1.0.28
paketo-buildpacks/nginx           0.17.8
paketo-buildpacks/source-removal  0.2.15
```

Will make another comment if the source-removal helped resolve the remaining files.

**Comment by voor** [comment]
Yep, looks like now that source-removal is in the regular participating listing I am able to achieve what I wanted.
